name: eis_model
channels:
  - conda-forge
  - defaults
dependencies:
  - fsspec=2024.6.1=pyhff2d567_0
  - h5py=3.11.0=nompi_py310habadce9_102
  - hdf5=1.14.3=nompi_h687a608_105
  - numpy=1.26.4=py310h4bfa8fc_0
  - pandas=2.2.2=py310hbf2a7f0_1
  - scikit-learn=1.5.1=py310h9d65eca_0
  - tensorflow=2.16.1=cpu_py310hf35338a_0
  - xarray=2024.7.0=pyhd8ed1ab_0
