name: eis_model
channels:
  - conda-forge
  - defaults
dependencies:
  - fsspec=2024.6.1
  - h5py=3.11.0
  - hdf5=1.14.3
  - numpy=1.26.4
  - pandas=2.2.2
  - scikit-learn=1.5.1
  - tensorflow=2.16.1
  - xarray=2024.7.0
